name: common
description: "common layer"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator:
  build_runner:

flutter: